# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    active: test
# ===================================================================
# Application specific properties
#
# Add your own application properties here
# ===================================================================
application:
  property:
    hello: test_hello