# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  messages:
    cache-duration: 1s

logging:
  level:
    org.springframework.web: info
    com.springboot.seed*: debug

# ===================================================================
# Application specific properties
#
# Add your own application properties here
# ===================================================================
application:
  property:
    hello: dev_hello