# ===================================================================
# Spring Boot configuration for the "batch" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================
spring:
  profiles:
    active: dev

application:
  isBatchServer: true
