spring:
  profiles:
    active: test

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

application:
  property:
    hello: test_hello