# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

spring:
  profiles:
    active: prod
# ===================================================================
# Application specific properties
#
# Add your own application properties here
# ===================================================================
application:
  property:
    hello: prod_hello
